### PR TITLE
Add JUnit tests for current tilesets and improve the file reading code.

### PR DESCRIPTION
**Pull request by enzanki-ars**

### CODE REVIEW

**Comment by enzanki-ars** [comment]
Still a work in progress...

**Comment by enzanki-ars** [comment]
Now the runner works!

**Comment by enzanki-ars** [comment]
`ConvertImageTest` currently takes 40 seconds to complete on my computer. At a later date, I will work on improving that.

**Comment by enzanki-ars** [comment]
For now though, the runner is good to merge and a great way to make sure no later changes break rendering any image.

**Comment by Choco31415** [comment]
After talking yesterday, we are holding off on adding alpha tilesets to the runner and squashing commits in general.

**Comment by enzanki-ars** [comment]
Squashed commits and added alpha tilesets. The PR is now ready to merge!

**Comment by Choco31415** [comment]
I like it! Accepted.

**Pull request merged**
